### ISSUE TITLE
Bw1 Editor

### ISSUE THREAD

**Issue by Priestyle** [FrostFalcon/FrostsBW2Editor#1]
Hey, could you make a bw1 editor also?

**Comment by FrostFalcon** [comment]
Done. https://github.com/FrostFalcon/FrostsBW2Editor/releases/tag/1.5.0
Let me know if you find any problems with it.

**Comment by Priestyle** [comment]
Hey what script file number lists all the ground items in black/white 1 by their index numbers? And what about for hidden items?

**Comment by FrostFalcon** [comment]
Ground items are in 864. If you open the overworld editor in the latest release, you can scroll through npcs to find the ground item you want. Take the script id -7000 to get the actual script id in 864 and edit the second command that sets a variable equal to the item id.

As for hidden items, I'm not sure on that one. You may want to ask the Kingdom of DS Romhacking discord. There'll be people there who are more familiar with bw1 than I am.
